spring:
  application:
    name: jobtracker

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enable: true
    baseline-on-migration: true
    location: classpath:db/migration

  server:
    port: 8080

  jwt:
    secret-key: ${JWT_SECRET_KEY}